In [2]:
import pandas as pd

/users/3/hassa940/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [3]:
df = pd.read_csv("results_per_section/gram8_plural" + "_results.csv")

In [ ]:
# load and stack the fourteen result files
root = Path("/results_per_section")
dfs = [pd.read_csv(f"resultsfp", sep="\t") for fp in root.glob("*.tsv")]
all_results = pd.concat(dfs, ignore_index=True)

In [4]:
df.sort_values(by='overall_accuracy', ascending=False)

,word1,word2,word3,true_word,section,candidate_1,candidate_2,candidate_3,candidate_4,candidate_5,candidate_6,candidate_7,candidate_8,candidate_9,candidate_10,freq_subset,rcond,measure,overall_accuracy
51946,woman,women,road,roads,gram8-plural,highway,highways,roadway,roadways,Roads,expressway,motorway,Highways,interstates,lanes,20000,0.005,mahalanobis_shifted_cosine,0.295045
51777,pineapple,pineapples,cat,cats,gram8-plural,feline,kitten,pup,puppies,kittens,pets,dog,raccoon,pet,poodle,20000,0.005,mahalanobis_shifted_cosine,0.295045
51493,mango,mangoes,bird,birds,gram8-plural,migratory_birds,turkeys,squirrel,owl,waterfowl,owls,geese,crows,turtles,parrot,20000,0.005,mahalanobis_shifted_cosine,0.295045
51494,mango,mangoes,bottle,bottles,gram8-plural,cans,bottled,carton,bottled_water,containers,plastic_bottles,beers,wines,cartons,beer,20000,0.005,mahalanobis_shifted_cosine,0.295045
51495,mango,mangoes,building,buildings,gram8-plural,Building,demolishing,renovating,built,constructing,demolish,build,demolition,apartments,refurbishing,20000,0.005,mahalanobis_shifted_cosine,0.295045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115434,mango,mangoes,child,children,gram8-plural,infant,newborn,baby,toddler,parents,mother,boy,kids,babies,siblings,100000,0.010,euclidean_distance,0.080330
115433,mango,mangoes,cat,cats,gram8-plural,dog,kitten,puppies,pup,puppy,pet,feline,dogs,kittens,animals,100000,0.010,euclidean_distance,0.080330
115432,mango,mangoes,car,cars,gram8-plural,vehicle,scooter,vehicles,truck,SUV,bikes,Mercedes,motorcycle,bike,motorcycles,100000,0.010,euclidean_distance,0.080330
115431,mango,mangoes,building,buildings,gram8-plural,AP_NewsCenter,built,By_Maureen_O'Gara,</s>,the,Building,constructing,newly_constructed,that,houses,100000,0.010,euclidean_distance,0.080330
55943,woman,women,snake,snakes,gram8-plural,</s>,By_Maureen_O'Gara,the,AP_NewsCenter,lizard,rat,all,reptiles,lizards,men,30000,0.001,euclidean_distance,0.080330

In [12]:
df.shape

(81200, 19)

In [13]:
df['overall_accuracy'].unique()

array([0.])

In [14]:
df.groupby(['freq_subset', 'rcond', 'measure'])['overall_accuracy'].first().reset_index()

    freq_subset  rcond                     measure  overall_accuracy
0         10000  0.001          euclidean_distance               0.0
1         10000  0.001          mahalanobis_cosine               0.0
2         10000  0.001        mahalanobis_distance               0.0
3         10000  0.001  mahalanobis_shifted_cosine               0.0
4         10000  0.001                naive_cosine               0.0
..          ...    ...                         ...               ...
95       100000  0.020          euclidean_distance               0.0
96       100000  0.020          mahalanobis_cosine               0.0
97       100000  0.020        mahalanobis_distance               0.0
98       100000  0.020  mahalanobis_shifted_cosine               0.0
99       100000  0.020                naive_cosine               0.0

[100 rows x 4 columns]

In [9]:
df.groupby(['freq_subset', 'rcond', 'measure'])['overall_accuracy'].first().reset_index().sort_values(by='overall_accuracy', ascending=False)

    freq_subset  rcond                     measure  overall_accuracy
96       100000  0.020          mahalanobis_cosine          0.082975
91       100000  0.010          mahalanobis_cosine          0.082975
86       100000  0.005          mahalanobis_cosine          0.082975
81       100000  0.001          mahalanobis_cosine          0.082975
88       100000  0.005  mahalanobis_shifted_cosine          0.062692
..          ...    ...                         ...               ...
57        30000  0.020        mahalanobis_distance          0.004917
62        50000  0.001        mahalanobis_distance          0.004302
77        50000  0.020        mahalanobis_distance          0.004302
67        50000  0.005        mahalanobis_distance          0.004302
72        50000  0.010        mahalanobis_distance          0.004302

[100 rows x 4 columns]